### ISSUE TITLE
Build broken Ubuntu 16.04

### ISSUE THREAD

**Issue by chriswier** [pololu/libpololu-avr#2]
I'm trying to build libpololu-avr for Ubuntu 16.04 x86_64.  While I can successfully compile it on 14.04, on 16.04 I'm getting the compilation errors below.

Prerequisites / Reproduce the issue:
1.  install Ubuntu 16.04
2.  apt-get install avrdude avr-libc gcc-avr git build-essential
3.  git clone http://github.com/pololu/libpololu-avr
4.  cd libpololu
5.  make

After compiling a few files, I get:

avr-g++ -g -Wall -mcall-prologues -mmcu=atmega324p  -DLIB_POLOLU -ffunction-sections -Os -I../../src/include -I../../ ../../src/OrangutanSPIMaster/../../src/OrangutanSPIMaster/OrangutanSPIMaster.cpp -c -o OrangutanSPIMaster.o
../../src/OrangutanSPIMaster/../../src/OrangutanSPIMaster/OrangutanSPIMaster.cpp: In static member function ‘static void OrangutanSPIMaster::init(unsigned char, unsigned char)’:
../../src/OrangutanSPIMaster/../../src/OrangutanSPIMaster/OrangutanSPIMaster.cpp:154:2: error: ‘SPCR’ was not declared in this scope
  SPCR = (1<<SPE) | (1<<MSTR) | (options & ~3) | (speed_divider & 3);  
  ^
../../src/OrangutanSPIMaster/../../src/OrangutanSPIMaster/OrangutanSPIMaster.cpp:154:13: error: ‘SPE’ was not declared in this scope
  SPCR = (1<<SPE) | (1<<MSTR) | (options & ~3) | (speed_divider & 3);  
             ^
../../src/OrangutanSPIMaster/../../src/OrangutanSPIMaster/OrangutanSPIMaster.cpp:154:24: error: ‘MSTR’ was not declared in this scope
  SPCR = (1<<SPE) | (1<<MSTR) | (options & ~3) | (speed_divider & 3);  
                        ^
../../src/OrangutanSPIMaster/../../src/OrangutanSPIMaster/OrangutanSPIMaster.cpp:155:2: error: ‘SPSR’ was not declared in this scope
  SPSR = (speed_divider & 4) ? 1 : 0;
  ^
../../src/OrangutanSPIMaster/../../src/OrangutanSPIMaster/OrangutanSPIMaster.cpp: In static member function ‘static unsigned char OrangutanSPIMaster::transmitAndDelay(unsigned char, unsigned char)’:
../../src/OrangutanSPIMaster/../../src/OrangutanSPIMaster/OrangutanSPIMaster.cpp:192:9: error: ‘SPCR’ was not declared in this scope
  if ( !(SPCR & (1<<SPE)) )
         ^
../../src/OrangutanSPIMaster/../../src/OrangutanSPIMaster/OrangutanSPIMaster.cpp:192:20: error: ‘SPE’ was not declared in this scope
  if ( !(SPCR & (1<<SPE)) )
                    ^
In file included from ../../src/OrangutanSPIMaster/../../src/OrangutanSPIMaster/OrangutanSPIMaster.cpp:33:0:
../../src/OrangutanSPIMaster/../../src/OrangutanSPIMaster/OrangutanSPIMaster.h:29:31: error: ‘CPHA’ was not declared in this scope
 #define SPI_EDGE_TRAILING (1<<CPHA)
                               ^
../../src/OrangutanSPIMaster/../../src/OrangutanSPIMaster/OrangutanSPIMaster.cpp:49:35: note: in expansion of macro ‘SPI_EDGE_TRAILING’
 #define SPI_DEFAULT_OPTIONS       SPI_EDGE_TRAILING
                                   ^
../../src/OrangutanSPIMaster/../../src/OrangutanSPIMaster/OrangutanSPIMaster.cpp:194:35: note: in expansion of macro ‘SPI_DEFAULT_OPTIONS’
   init(SPI_DEFAULT_SPEED_DIVIDER, SPI_DEFAULT_OPTIONS);
                                   ^
../../src/OrangutanSPIMaster/../../src/OrangutanSPIMaster/OrangutanSPIMaster.cpp:197:8: error: ‘SPCR’ was not declared in this scope
  if (!(SPCR&(1<<MSTR)))
        ^
../../src/OrangutanSPIMaster/../../src/OrangutanSPIMaster/OrangutanSPIMaster.cpp:197:17: error: ‘MSTR’ was not declared in this scope
  if (!(SPCR&(1<<MSTR)))
                 ^
../../src/OrangutanSPIMaster/../../src/OrangutanSPIMaster/OrangutanSPIMaster.cpp:208:2: error: ‘SPDR’ was not declared in this scope
  SPDR = data;
  ^
../../src/OrangutanSPIMaster/../../src/OrangutanSPIMaster/OrangutanSPIMaster.cpp:211:10: error: ‘SPSR’ was not declared in this scope
  while(!(SPSR & (1<<SPIF)))
          ^
../../src/OrangutanSPIMaster/../../src/OrangutanSPIMaster/OrangutanSPIMaster.cpp:211:21: error: ‘SPIF’ was not declared in this scope
  while(!(SPSR & (1<<SPIF)))
                     ^
../../src/OrangutanSPIMaster/../../src/OrangutanSPIMaster/OrangutanSPIMaster.cpp:213:9: error: ‘SPCR’ was not declared in this scope
   if (!(SPCR & (1<<MSTR)))
         ^
../../src/OrangutanSPIMaster/../../src/OrangutanSPIMaster/OrangutanSPIMaster.cpp:213:20: error: ‘MSTR’ was not declared in this scope
   if (!(SPCR & (1<<MSTR)))
                    ^
../../src/OrangutanSPIMaster/../../src/OrangutanSPIMaster/OrangutanSPIMaster.cpp:231:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
../template.mk:35: recipe for target 'OrangutanSPIMaster.o' failed
make[1]: **\* [OrangutanSPIMaster.o] Error 1
make[1]: Leaving directory '/home/chris/software-builds/libpololu-avr/devices/atmega324p'
Makefile:39: recipe for target 'library_files' failed
make: **\* [library_files] Error 2

---

I noticed that there is a difference in packages for Ubuntu 16.04 from 14.04; the dpkg listing is below:

Ubuntu 14.04:  (dpkg --list | grep avr)
ii  avr-libc                                  1:1.8.0-4.1                                         all          Standard C library for Atmel AVR development
ii  avrdude                                   6.0.1-1                                             amd64        software for programming Atmel AVR microcontrollers
ii  binutils-avr                              2.23.1-2.1                                          amd64        Binary utilities supporting Atmel's AVR targets
ii  gcc-avr                                   1:4.8-2.1                                           amd64        The GNU C compiler (cross compiler for avr)

Ubuntu 16.04:  (dpkg --list | grep avr)
ii  avr-libc                                    1:1.8.0+Atmel3.5.0-1                                all          Standard C library for Atmel AVR development
ii  avrdude                                     6.2-5                                               amd64        software for programming Atmel AVR microcontrollers
ii  binutils-avr                                2.25+Atmel3.5.0-2                                   amd64        Binary utilities supporting Atmel's AVR targets
ii  gcc-avr                                     1:4.9.2+Atmel3.5.0-1                                amd64        GNU C compiler (cross compiler for avr)

Any help would be appreciated.

**Comment by DavidEGrayson** [comment]
Hello.  Thanks for the bug report.  I was able to reproduce it in Ubuntu 15.10, and I fixed it with commit 9e3c88fb29dc8a469c9883146cb98c9cac5202b2.  Feel free to reopen this issue if that commit doesn't fix the problem for you.
